### ISSUE TITLE
Data Retention

### ISSUE THREAD

**Issue by DrBeta** [athaun/Eclipse-OS#4]
**Is your feature request related to a problem? Please describe.**
Why can't I save my data, I push restart, and I need to set up again
**Describe the solution you'd like**
When I push restart, I would like it to save my username and password and everything I've done.
Maybe getting of of khan academy could help

**Comment by athaun** [comment]
Thank you for raising this issue to our attention, we are thinking about the possibility of saving data through program restarts, but it isn't a main concern at the moment. I agree that Khan Academy limits us, but we are doing this purely for fun. 
Thanks, Asher

**Comment by DrBeta** [comment]
Got it! I was referenced to this from @xXMoonLightXx but I thought that this serious, like you meant to put it on a computer. That probably could be done, just find a lite Linux wrapper and make something like a Chromebook.

**Comment by bhavjitChauhan** [comment]
This will be implemented in the future. Although the data will be erased when the website is reloaded (we can't do anything about this without breaking KA's guidelines), restarting the program will not require you to input most of the information, load the assets again, etc. in the future.

**Comment by athaun** [comment]
> Got it! I was referenced to this from @xXMoonLightXx but I thought that this serious, like you meant to put it on a computer. That probably could be done, just find a lite Linux wrapper and make something like a Chromebook.

I do like the idea, but at the time, it is beyond my Linux skills, I am however working on a custom linux distro (slowly), and I will definitely take some inspiration from Eclipse OS. But, I definitely like the idea, and positive feedback.
Thanks, Asher (Lead developer for Eclipse OS)
