### ISSUE TITLE
More Than One Account

### ISSUE THREAD

**Issue by NehemiahAT** [athaun/Eclipse-OS#5]
**Is your feature request related to a problem? Please describe.**
I was just wondering if you could allow more than one account in the OS (in the future, I mean). I was meaning to make this a pull request, but the Contributing Guidelines said I needed to ask the lead developers if I want to make a new feature.

**Describe the solution you'd like**
I'd be glad to add the feature myself. I have not devised a precise solution yet in case I went through all that work only for my feature to be rejected. I know how frustrating this can be. 

**Describe alternatives you've considered**
It would be fine if you did it, though. I just don't want to give you too much work, considering how much work it must've already taken.

**Additional context**
What should the new version number be and would you or I release it?

**Comment by bhavjitChauhan** [comment]
I suggested this to the lead developers before but they said it would be too complicated. 

I was thinking of just creating a `User` object and replacing `system.username` to `system.currentUser` which would hold the `User` object. 

Feel free to create a PR, I will review it and make any changes if necessary before merging.

**Comment by NehemiahAT** [comment]
@bhavjitChauhan Thank you.

I'm working on my Enigma-Commercial-Version repository at the moment, but I'll try to do it as soon as I can. They don't have to worry about the complexity. I'll to the hear-tearing.

**Comment by NehemiahAT** [comment]
@bhavjitChauhan I think I might try to do something different so it can list all the users in the variable describing the OS.

**Comment by bhavjitChauhan** [comment]
Feel free to do it however you want, I was just listing a possibility. 

Thanks for checking EOS out.

**Comment by NehemiahAT** [comment]
@bhavjitChauhan Thank you. I might do that and just add the user using the OS into an array, deleting things that are repeated. 

You're welcome.
